#Settings for the application

# Whether to encrypt private keys
private_key_encryption: true

# Number of threads to use for processing wallets
threads: 1

# Number of retries for failed action
retry: 3

# BY DEFAULT: [0,0] - all wallets
# Example: [2, 6] will run wallets 2,3,4,5,6
# [4,4] will run only wallet 4
range_wallets_to_run: [0,0]

# Working only if range_wallet_to_run = [0,0] 
# BY DEFAULT: [] - all wallets 
# Example: [1, 3, 8] - will run only 1, 3 and 8 wallets
exact_wallets_to_run: []

# Whether to shuffle the list of wallets before processing
shuffle_wallets: true

# Hide wallet address in logs
hide_wallet_address_log: true

# the log level for the application. Options: DEBUG, INFO, WARNING, ERROR
log_level : INFO

# Discord: Use different proxies to join discord server
discord_proxy: false

#Check for git updates
check_git_updates: true

# Api Key from https://dash.capmonster.cloud/
capmonster_api_key: ''

# Delay before running the same wallet again after it has completed all actions (1 - 2 hrs default)
random_pause_wallet_after_completion:
  min: 3600
  max: 7200

# Random pause between actions in seconds
random_pause_between_actions:
  min: 20
  max: 30

# Random pause between actions in seconds
random_pause_start_wallet:
  min: 0
  max: 60

# Swap percent of coin balance
swap_percent:
  min: 5
  max: 30

# Swap action count
swaps_count:
  min: 15
  max: 30

# Liquidity percent of native coin balance
liquidity_percent:
  min: 1
  max: 3

# Liquidity action count
liquidity_count:
  min: 5
  max: 10  

# Send tokens to friends action count
tips_count:
  min: 15
  max: 30  

# Autostake action count
autostake_count:
  min: 1
  max: 4

# Autostake percent of coin balance
autostake_percent:
  min: 5
  max: 10  

# CFD Trading Brokex futures percent of USDT
brokex_percent:
  min: 1
  max: 2

# CFD Trading Brokex position count
brokex_count:
  min: 5
  max: 10

# Lending count
lending_count:
  min: 5
  max: 10

# Bitverse position count
bitverse_count:
  min: 5
  max: 10

# Bitverse position percent
bitverse_percent:
  min: 35
  max: 60

# R2 Action Count
r2_count:
  min: 7
  max: 15

# R2 Swap Percent
r2_swap:
  min: 15
  max: 25

# R2 Stake Percent
r2_stake:
  min: 5
  max: 10

# Spout Percent
spout_percent:
  min: 1
  max: 3

# Spout Swap Count
spout_count:
  min: 5
  max: 10

# Gotchipus Send tokens count
gotchipus_count:
  min: 5
  max: 10

# Mint Pharos Identity Service action count
domains_count:
  min: 1
  max: 5

# Refill from monad (minimum: 0.01 MON)
monad_transfer:
  min: 0.02
  max: 1
  
# Asseto activity count
asseto_count:
  min: 4
  max: 8

# Asseto USDT deposit percent
asseto_percent:
  min: 35
  max: 60

# Zenit Liquidity for new season
zenith_liq:
  min: 41
  max: 50

# Aquaflux Deposit/Structure for new season
aquaflux_deposit:
  min: 41
  max: 50

# Aquaflux Earn for new season
aquaflux_earn:
  min: 41
  max: 50

# Bitverse Swap Count for new season
bitverse_spot:
  min: 30
  max: 50

# Bitverse Liquidity Count for new season
bitverse_liquidity:
  min: 30
  max: 50

# Bitverse Liquidity Percent for new season
bitverse_liquidity_percent:
  min: 2
  max: 5

# Invite Codes for pharos network, example [invite_code1, invite_code2]
invite_codes: [] 
